server:
  port: 8081

spring:
  application:
    name: item-service

  datasource:
    url: jdbc:postgresql://localhost:5432/item_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none # important when using Liquibase!
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
